amcl:
  ros__parameters:
    use_sim_time: true
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_footprint
    scan_topic: /scan
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    laser_model_type: likelihood_field
    min_particles: 300
    max_particles: 1000
    max_beams: 60
    update_min_d: 0.02
    update_min_a: 0.02
    tf_broadcast: true
    transform_tolerance: 0.5
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
